#!/bin/sh

sleep 20

gov=/sys/devices/system/cpu/cpufreq
stune=/dev/stune
cpu_set=/dev/cpuset

#CPU-Tweaks
for governor in $gov/*/scaling_governor
    do
        echo "schedutil" $governor
done

for policy_0 in $gov/policy0/schedutil
    do 
        echo 300 > $policy_0/down_rate_limit_us
        echo 1036800 > $policy_0/hispeed_freq
        echo 300 > $policy_0/up_rate_limit_us
done

for policy_4 in $gov/policy4/schedutil
    do
        echo 300 > $policy_4/down_rate_limit_us
        echo 1497600 > $policy_4/hispeed_freq
        echo 700 > $policy_4/up_rate_limit_us
done

for policy_7 in $gov/policy7/schedutil
    do
        echo 300 > $policy_7/down_rate_limit_us
        echo 2016000 > $policy_7/hispeed_freq
        echo 900 > $policy_7/up_rate_limit_us
done

for gov_param in $gov/*/schedutil
    do 
        echo 90 > $gov_param/hispeed_load
        echo 1 > $gov_param/pl
done

for core_0 in /sys/devices/system/cpu/cpu0/core_ctl
    do 
        echo 1 > $core_0/enable
        echo 4 > $core_0/max_cpus
        echo 0 > $core_0/min_cpus
        echo 10 > $core_0/busy_down_thres
        echo 10 > $core_0/busy_up_thres
done
for core_4 in /sys/devices/system/cpu/cpu4/core_ctl
    do 
        echo 1 > $core_4/enable
        echo 3 > $core_4/max_cpus
        echo 0 > $core_4/min_cpus
        echo 40 > $core_4/busy_down_thres
        echo 60 > $core_4/busy_up_thres
done
for core_7 in /sys/devices/system/cpu/cpu7/core_ctl
    do 
        echo 1 > $core_7/enable
        echo 1 > $core_7/max_cpus
        echo 0 > $core_7/min_cpus
        echo 90 > $core_7/busy_down_thres
        echo 90 > $core_7/busy_up_thres
done

#stune-Boost-Tweaks
for audio_app in $stune/audio-app
    do 
        echo 0 > $audio_app/schedtune.boost
        echo 0 > $audio_app/schedtune.colocate
        echo 0 > $audio_app/schedtune.prefer_idle
        echo 1 > $audio_app/schedtune.sched_boost_no_override
done
    echo "2-3" > $cpu_set/audio-app/cpus
for background in $stune/background
    do 
        echo 0 > $background/schedtune.boost
        echo 0 > $background/schedtune.colocate
        echo 0 > $background/schedtune.prefer_idle
        echo 1 > $background/schedtune.sched_boost_no_override
done
    echo "0-1" > $cpu_set/background/cpus
for camera_daemon in $stune/camera-daemon
    do 
        echo 0 > $camera_daemon/schedtune.boost
        echo 0 > $camera_daemon/schedtune.colocate
        echo 0 > $camera_daemon/schedtune.prefer_idle
        echo 1 > $camera_daemon/schedtune.sched_boost_no_override
done
    echo "0-3" > $cpu_set/camera-daemon/cpus
for foreground in $stune/foreground
    do 
        echo 0 > $foreground/schedtune.boost
        echo 0 > $foreground/schedtune.colocate
        echo 0 > $foreground/schedtune.prefer_idle
        echo 1 > $foreground/schedtune.sched_boost_no_override
done
    echo "4-6" > $cpu_set/foreground/cpus
for nnapi_hal in $stune/nnapi-hal
    do 
        echo 0 > $nnapi_hal/schedtune.boost
        echo 0 > $nnapi_hal/schedtune.colocate
        echo 0 > $nnapi_hal/schedtune.prefer_idle
        echo 1 > $nnapi_hal/schedtune.sched_boost_no_override
done
for rt in $stune/rt
    do 
        echo 0 > $rt/schedtune.boost
        echo 0 > $rt/schedtune.colocate
        echo 0 > $rt/schedtune.prefer_idle
        echo 1 > $rt/schedtune.sched_boost_no_override
done
for top_app in $stune/top-app
    do 
        echo 0 > $top_app/schedtune.boost
        echo 0 > $top_app/schedtune.colocate
        echo 0 > $top_app/schedtune.prefer_idle
        echo 1 > $top_app/schedtune.sched_boost_no_override
done
    echo "0-7" > $cpu_set/top-apps/cpus
for general in $stune
    do 
        echo 0 > $general/schedtune.boost
        echo 0 > $general/schedtune.colocate
        echo 0 > $general/schedtune.prefer_idle
        echo 0 > $general/schedtune.sched_boost_no_override
done
    echo "0-7" > $cpu_set/cpus

#I/O-scheduler-Tweaks
for mmcblk0 in /sys/block/mmcblk0/queue
    do 
        echo "cfq" > $mmcblk0/scheduler
        echo 0 > $mmcblk0/add_random
        echo 0 > $mmcblk0/iostats
        echo 512 > $mmcblk0/nr_requests
        echo 512 > $mmcblk0/read_ahead_kb
done
for sda in /sys/block/sda/queue
    do 
        echo "cfq" > $sda/scheduler
        echo 0 > $sda/add_random
        echo 0 > $sda/iostats
        echo 512 > $sda/nr_requests
        echo 512 > $sda/read_ahead_kb
done
for sdb in /sys/block/sdb/queue
    do 
        echo "cfq" > $sdb/scheduler
        echo 0 > $sdb/add_random
        echo 0 > $sdb/iostats
        echo 512 > $sdb/nr_requests
        echo 512 > $sdb/read_ahead_kb
done
for sdc in /sys/block/sdc/queue
    do 
        echo "cfq" > $sdc/scheduler
        echo 0 > $sdc/add_random
        echo 0 > $sdc/iostats
        echo 512 > $sdc/nr_requests
        echo 512 > $sdc/read_ahead_kb
done
for sdd in /sys/block/sdd/queue
    do 
        echo "cfq" > $sdd/scheduler
        echo 0 > $sdd/add_random
        echo 0 > $sdd/iostats
        echo 512 > $sdd/nr_requests
        echo 512 > $sdd/read_ahead_kb
done
for sde in /sys/block/sde/queue
    do 
        echo "cfq" > $sde/scheduler
        echo 0 > $sde/add_random
        echo 0 > $sde/iostats
        echo 512 > $sde/nr_requests
        echo 512 > $sde/read_ahead_kb
done
for sdf in /sys/block/sdf/queue
    do 
        echo "cfq" > $sdf/scheduler
        echo 0 > $sdf/add_random
        echo 0 > $sdf/iostats
        echo 512 > $sdf/nr_requests
        echo 512 > $sdf/read_ahead_kb
done

#kernel-Tweaks
for kernel in /proc/sys/kernel
    do 
        echo 20 > $kernel/perf_cpu_time_max_percent
        echo 0 > $kernel/sched_child_runs_first
        echo 25 > $kernel/sched_min_task_util_for_colocation
        echo "off" > $kernel/printk_devmsg
        echo 205 > $kernel/sched_lib_mask_force
        echo "libunity.so, libUE4.so" > $kernel/sched_lib_name
done

exit 0
