#!/bin/sh

sleep 3

display=/sys/devices/platform

#displayMods
for primary in $display/soc/soc:qcom,dsi-display-primary
  do
    echo 1 > $primary/hbm
    echo 1 > $primary/cabc
done
for kcal in $display/kcal_ctrl.0
  do
    echo 1 > $kcal/kcal_enable
    echo 225 225 237 > $kcal/kcal
    echo 264 > $kcal/kcal_cont
    echo 35 > $kcal/kcal_min
    echo 277 > $kcal/kcal_sat
    echo 250 > $kcal/kcal_val
done

#ioScheduler
for mmcblk0 in /sys/block/mmcblk0/queue
    do 
        echo "cfq" > $mmcblk0/scheduler
        echo 0 > $mmcblk0/add_random
        echo 0 > $mmcblk0/iostats
        echo 256 > $mmcblk0/nr_requests
        echo 512 > $mmcblk0/read_ahead_kb
done
for sda in /sys/block/sda/queue
    do 
        echo "cfq" > $sda/scheduler
        echo 0 > $sda/add_random
        echo 0 > $sda/iostats
        echo 256 > $sda/nr_requests
        echo 512 > $sda/read_ahead_kb
done
for sdb in /sys/block/sdb/queue
    do 
        echo "cfq" > $sdb/scheduler
        echo 0 > $sdb/add_random
        echo 0 > $sdb/iostats
        echo 256 > $sdb/nr_requests
        echo 512 > $sdb/read_ahead_kb
done
for sdc in /sys/block/sdc/queue
    do 
        echo "cfq" > $sdc/scheduler
        echo 0 > $sdc/add_random
        echo 0 > $sdc/iostats
        echo 256 > $sdc/nr_requests
        echo 512 > $sdc/read_ahead_kb
done
for sdd in /sys/block/sdd/queue
    do 
        echo "cfq" > $sdd/scheduler
        echo 0 > $sdd/add_random
        echo 0 > $sdd/iostats
        echo 256 > $sdd/nr_requests
        echo 512 > $sdd/read_ahead_kb
done
for sde in /sys/block/sde/queue
    do 
        echo "cfq" > $sde/scheduler
        echo 0 > $sde/add_random
        echo 0 > $sde/iostats
        echo 256 > $sde/nr_requests
        echo 512 > $sde/read_ahead_kb
done
for sdf in /sys/block/sdf/queue
    do 
        echo "cfq" > $sdf/scheduler
        echo 0 > $sdf/add_random
        echo 0 > $sdf/iostats
        echo 256 > $sdf/nr_requests
        echo 512 > $sdf/read_ahead_kb
done

#kernelMods
for kernel in /proc/sys/kernel
    do 
        echo 20 > $kernel/perf_cpu_time_max_percent
        echo 0 > $kernel/sched_child_runs_first
        echo 25 > $kernel/sched_min_task_util_for_colocation
        echo "off" > $kernel/printk_devmsg
        echo 205 > $kernel/sched_lib_mask_force
        echo "libunity.so, libUE4.so" > $kernel/sched_lib_name
done

exit 0