#!/system/bin/sh

display=/sys/devices/platform
for path in $display/soc/soc:qcom,dsi-display-primary $display/kcal_ctrl.0; do
    case "$path" in
        $display/soc/soc:qcom,dsi-display-primary)
            echo 1 > $path/hbm
            echo 1 > $path/cabc
            ;;
        $display/kcal_ctrl.0)
            echo 1 > $path/kcal_enable
            echo 252 252 255 > $path/kcal
            echo 255 > $path/kcal_cont
            echo 35 > $path/kcal_min
            echo 263 > $path/kcal_sat
            echo 255 > $path/kcal_val
            ;;
    esac
done