#!/bin/sh

sleep 30

gov=/sys/devices/system/cpu/cpufreq
stune=/dev/stune
cpu_set=/dev/cpuset

#cpuMods
echo $(grep -q 'blu_schedutil' $gov/*/scaling_available_governor && echo "blu_schedutil" || echo "schedutil") | tee $gov/*/scaling_governor

for gov_param in $gov/*/schedutil
    do 
        echo 500 > $gov_param/down_rate_limit_us
        echo 90 > $gov_param/hispeed_load
        echo 1 > $gov_param/pl
done

for policy_0 in $gov/policy0/schedutil
    do 
        echo 1036800 > $policy_0/hispeed_freq
        echo 300 > $policy_0/up_rate_limit_us
done
for policy_4 in $gov/policy4/schedutil
    do
        echo 1497600 > $policy_4/hispeed_freq
        echo 700 > $policy_4/up_rate_limit_us
done
for policy_7 in $gov/policy7/schedutil
    do
        echo 2016000 > $policy_7/hispeed_freq
        echo 900 > $policy_7/up_rate_limit_us
done

#coreControl
for core_0 in /sys/devices/system/cpu/cpu0/core_ctl
    do 
        echo 1 > $core_0/enable
        echo 4 > $core_0/max_cpus
        echo 0 > $core_0/min_cpus
        echo 10 > $core_0/busy_down_thres
        echo 10 > $core_0/busy_up_thres
done
for core_4 in /sys/devices/system/cpu/cpu4/core_ctl
    do 
        echo 1 > $core_4/enable
        echo 3 > $core_4/max_cpus
        echo 0 > $core_4/min_cpus
        echo 40 > $core_4/busy_down_thres
        echo 60 > $core_4/busy_up_thres
done
for core_7 in /sys/devices/system/cpu/cpu7/core_ctl
    do 
        echo 1 > $core_7/enable
        echo 1 > $core_7/max_cpus
        echo 0 > $core_7/min_cpus
        echo 90 > $core_7/busy_down_thres
        echo 90 > $core_7/busy_up_thres
done

#stuneBoost
for audio_app in $stune/audio-app
    do 
        echo 0 > $audio_app/schedtune.boost
        echo 0 > $audio_app/schedtune.colocate
        echo 0 > $audio_app/schedtune.prefer_idle
        echo 1 > $audio_app/schedtune.sched_boost_no_override
done
    echo "2-3" > $cpu_set/audio-app/cpus
for background in $stune/background
    do 
        echo 0 > $background/schedtune.boost
        echo 0 > $background/schedtune.colocate
        echo 0 > $background/schedtune.prefer_idle
        echo 1 > $background/schedtune.sched_boost_no_override
done
    echo "0-1" > $cpu_set/background/cpus
for camera_daemon in $stune/camera-daemon
    do 
        echo 0 > $camera_daemon/schedtune.boost
        echo 0 > $camera_daemon/schedtune.colocate
        echo 0 > $camera_daemon/schedtune.prefer_idle
        echo 1 > $camera_daemon/schedtune.sched_boost_no_override
done
    echo "2-3,5" > $cpu_set/camera-daemon/cpus
for foreground in $stune/foreground
    do 
        echo 0 > $foreground/schedtune.boost
        echo 0 > $foreground/schedtune.colocate
        echo 0 > $foreground/schedtune.prefer_idle
        echo 1 > $foreground/schedtune.sched_boost_no_override
done
    echo "0-1,4" > $cpu_set/foreground/cpus
for nnapi_hal in $stune/nnapi-hal
    do 
        echo 0 > $nnapi_hal/schedtune.boost
        echo 0 > $nnapi_hal/schedtune.colocate
        echo 0 > $nnapi_hal/schedtune.prefer_idle
        echo 1 > $nnapi_hal/schedtune.sched_boost_no_override
done
for rt in $stune/rt
    do 
        echo 0 > $rt/schedtune.boost
        echo 0 > $rt/schedtune.colocate
        echo 0 > $rt/schedtune.prefer_idle
        echo 1 > $rt/schedtune.sched_boost_no_override
done
for top_app in $stune/top-app
    do 
        echo 0 > $top_app/schedtune.boost
        echo 1 > $top_app/schedtune.colocate
        echo 0 > $top_app/schedtune.prefer_idle
        echo 1 > $top_app/schedtune.sched_boost_no_override
done
    echo "0-6" > $cpu_set/top-app/cpus
for general in $stune
    do 
        echo 0 > $general/schedtune.boost
        echo 0 > $general/schedtune.colocate
        echo 0 > $general/schedtune.prefer_idle
        echo 0 > $general/schedtune.sched_boost_no_override
done

#vmMods
for zram0 in /sys/block/zram0/queue
    do 
        echo 0 > $zram0/add_random
        echo 0 > $zram0/iostats
        echo 128 > $zram0/nr_requests
        echo 1024 > $zram0/read_ahead_kb
done
for dm0 in /sys/block/dm-0/queue
    do 
        echo 0 > $dm0/add_random
        echo 0 > $dm0/iostats
        echo 128 > $dm0/nr_requests
        echo 1024 > $dm0/read_ahead_kb
done
for dm1 in /sys/block/dm-1/queue
    do 
        echo 0 > $dm1/add_random
        echo 0 > $dm1/iostats
        echo 128 > $dm1/nr_requests
        echo 1024 > $dm1/read_ahead_kb
done

for virtual_mem in /proc/sys/vm
    do 
        echo 60 > $virtual_mem/swappiness
        echo 10 > $virtual_mem/dirty_ratio
        echo 20 > $virtual_mem/dirty_background_ratio
        echo 500 > $virtual_mem/dirty_writeback_centisecs
        echo 3000 > $virtual_mem/dirty_expire_centisecs
        echo 90 > $virtual_mem/vfs_cache_pressure
        echo 0 > $virtual_mem/page-cluster
        echo 0 > $virtual_mem/stat_interval
done

exit 0