#!/bin/sh

sleep 20

#unity-tweak
chmod 0444 /sys/devices/system/cpu/cpu0/cpu_capacity
chmod 0444 /sys/devices/system/cpu/cpu1/cpu_capacity
chmod 0444 /sys/devices/system/cpu/cpu2/cpu_capacity
chmod 0444 /sys/devices/system/cpu/cpu3/cpu_capacity
chmod 0444 /sys/devices/system/cpu/cpu4/cpu_capacity
chmod 0444 /sys/devices/system/cpu/cpu5/cpu_capacity
chmod 0444 /sys/devices/system/cpu/cpu6/cpu_capacity
chmod 0444 /sys/devices/system/cpu/cpu7/cpu_capacity

chmod 0444 /sys/devices/system/cpu/cpu0/topology/physical_package_id
chmod 0444 /sys/devices/system/cpu/cpu1/topology/physical_package_id
chmod 0444 /sys/devices/system/cpu/cpu2/topology/physical_package_id
chmod 0444 /sys/devices/system/cpu/cpu3/topology/physical_package_id
chmod 0444 /sys/devices/system/cpu/cpu4/topology/physical_package_id
chmod 0444 /sys/devices/system/cpu/cpu5/topology/physical_package_id
chmod 0444 /sys/devices/system/cpu/cpu6/topology/physical_package_id
chmod 0444 /sys/devices/system/cpu/cpu7/topology/physical_package_id

echo 0 > /sys/devices/system/cpu/cpu0/core_ctl/enable
echo 0 > /sys/devices/system/cpu/cpu1/core_ctl/enable
echo 0 > /sys/devices/system/cpu/cpu2/core_ctl/enable
echo 0 > /sys/devices/system/cpu/cpu3/core_ctl/enable
echo 0 > /sys/devices/system/cpu/cpu4/core_ctl/enable
echo 0 > /sys/devices/system/cpu/cpu5/core_ctl/enable
echo 0 > /sys/devices/system/cpu/cpu6/core_ctl/enable
echo 0 > /sys/devices/system/cpu/cpu7/core_ctl/enable

#CPU-tweak
echo schedutil > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo schedutil > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
echo schedutil > /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor
echo schedutil > /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor
echo schedutil > /sys/devices/system/cpu/cpu4/cpufreq/scaling_governor
echo schedutil > /sys/devices/system/cpu/cpu5/cpufreq/scaling_governor
echo schedutil > /sys/devices/system/cpu/cpu6/cpufreq/scaling_governor
echo schedutil > /sys/devices/system/cpu/cpu7/cpufreq/scaling_governor

#hbm
echo 1 > /sys/devices/platform/soc/soc:qcom,dsi-display-primary/hbm

#cabc
echo 1 > /sys/devices/platform/soc/soc:qcom,dsi-display-primary/cabc

#fake-amoled
echo 1 > /sys/devices/platform/kcal_ctrl.0/kcal_enable
echo 225 225 237 > /sys/devices/platform/kcal_ctrl.0/kcal
echo 264 > /sys/devices/platform/kcal_ctrl.0/kcal_cont
echo 35 > /sys/devices/platform/kcal_ctrl.0/kcal_min
echo 277 > /sys/devices/platform/kcal_ctrl.0/kcal_sat
echo 250 > /sys/devices/platform/kcal_ctrl.0/kcal_val

#stune-boost-audioApp
echo 0 > /dev/stune/audio-app/schedtune.boost
echo 0 > /dev/stune/audio-app/schedtune.colocate
echo 0 > /dev/stune/audio-app/schedtune.prefer_idle
echo 1 > /dev/stune/audio-app/schedtune.sched_boost_no_override
echo "2-3" > /dev/cpuset/audio-app/cpus

#stune-boost-background
echo 0 > /dev/stune/background/schedtune.boost
echo 0 > /dev/stune/background/schedtune.colocate
echo 0 > /dev/stune/background/schedtune.prefer_idle
echo 1 > /dev/stune/background/schedtune.sched_boost_no_override
echo "0-1" > /dev/cpuset/background/cpus

#stune-boost-cameraDaemon
echo 0 > /dev/stune/camera-daemon/schedtune.boost
echo 1 > /dev/stune/camera-daemon/schedtune.colocate
echo 0 > /dev/stune/camera-daemon/schedtune.prefer_idle
echo 1 > /dev/stune/camera-daemon/schedtune.sched_boost_no_override
echo "0-3" > /dev/cpuset/camera-daemon/cpus

#stune-boost-foreground
echo 10 > /dev/stune/foreground/schedtune.boost
echo 0 > /dev/stune/foreground/schedtune.colocate
echo 1 > /dev/stune/foreground/schedtune.prefer_idle
echo 0 > /dev/stune/foreground/schedtune.sched_boost_no_override
echo "4-6" > /dev/cpuset/foreground/cpus

#stune-boost-nnapi-HAL
echo 15 > /dev/stune/nnapi-hal/schedtune.boost
echo 0 > /dev/stune/nnapi-hal/schedtune.colocate
echo 1 > /dev/stune/nnapi-hal/schedtune.prefer_idle
echo 0 > /dev/stune/nnapi-hal/schedtune.sched_boost_no_override

#stune-boost-rt
echo 0 > /dev/stune/rt/schedtune.boost
echo 1 > /dev/stune/rt/schedtune.colocate
echo 0 > /dev/stune/rt/schedtune.prefer_idle
echo 0 > /dev/stune/rt/schedtune.sched_boost_no_override

#stune-boost-topApp
echo 15 > /dev/stune/top-app/schedtune.boost
echo 1 > /dev/stune/top-app/schedtune.colocate
echo 1 > /dev/stune/top-app/schedtune.prefer_idle
echo 0 > /dev/stune/top-app/schedtune.sched_boost_no_override
echo "0-7" > /dev/cpuset/top-apps/cpus

#stune-boost-General
echo 10 > /dev/stune/schedtune.boost
echo 0 > /dev/stune/schedtune.colocate
echo 1 > /dev/stune/schedtune.prefer_idle
echo 0 > /dev/stune/schedtune.sched_boost_no_override
echo "0-7" > /dev/cpuset/cpus

#cpu-governor-param
echo 10000 > /sys/devices/system/cpu/cpufreq/policy0/schedutil/down_rate_limit_us
echo 1785000 > /sys/devices/system/cpu/cpufreq/policy0/schedutil/hispeed_freq
echo 90 > /sys/devices/system/cpu/cpufreq/policy0/schedutil/hispeed_load
echo 1 > /sys/devices/system/cpu/cpufreq/policy0/schedutil/pl
echo 500 > /sys/devices/system/cpu/cpufreq/policy0/schedutil/up_rate_limit_us

echo 15000 > /sys/devices/system/cpu/cpufreq/policy4/schedutil/down_rate_limit_us
echo 1804000 > /sys/devices/system/cpu/cpufreq/policy4/schedutil/hispeed_freq
echo 90 > /sys/devices/system/cpu/cpufreq/policy4/schedutil/hispeed_load
echo 1 > /sys/devices/system/cpu/cpufreq/policy4/schedutil/pl
echo 500 > /sys/devices/system/cpu/cpufreq/policy4/schedutil/up_rate_limit_us

echo 20000 > /sys/devices/system/cpu/cpufreq/policy7/schedutil/down_rate_limit_us
echo 1804000 > /sys/devices/system/cpu/cpufreq/policy7/schedutil/hispeed_freq
echo 90 > /sys/devices/system/cpu/cpufreq/policy7/schedutil/hispeed_load
echo 1 > /sys/devices/system/cpu/cpufreq/policy7/schedutil/pl
echo 500 > /sys/devices/system/cpu/cpufreq/policy7/schedutil/up_rate_limit_us

#TCP-mods
echo 1 > /proc/sys/net/ipv4/tcp_ecn
echo 3 > /proc/sys/net/ipv4/tcp_fastopen
echo 0 > /proc/sys/net/ipv4/tcp_syncookies
echo 1 > /proc/sys/net/ipv4/tcp_low_latency

#ZRam-mods
echo 15 > /proc/sys/vm/swappiness
echo 10 > /proc/sys/vm/dirty_ratio
echo 20 > /proc/sys/vm/dirty_background_ratio
echo 1500 > /proc/sys/vm/dirty_writeback_centisecs
echo 1500 > /proc/sys/vm/dirty_expire_centisecs
echo 100 > /proc/sys/vm/vfs_cache_pressure
echo 0 > /proc/sys/vm/page-cluster
echo 0 > /proc/sys/vm/stat_interval

#I/O-scheduler-mods
echo "cfq" > /sys/block/mmcblk0/queue/scheduler
echo "cfq" > /sys/block/sda/queue/scheduler
echo "cfq" > /sys/block/sdb/queue/scheduler
echo "cfq" > /sys/block/sdc/queue/scheduler
echo "cfq" > /sys/block/sdd/queue/scheduler
echo "cfq" > /sys/block/sde/queue/scheduler
echo "cfq" > /sys/block/sdf/queue/scheduler

#I/O-addRandom-mods
echo 0 > /sys/block/mmcblk0/queue/add_random
echo 0 > /sys/block/sda/queue/add_random
echo 0 > /sys/block/sdb/queue/add_random
echo 0 > /sys/block/sdc/queue/add_random
echo 0 > /sys/block/sdd/queue/add_random
echo 0 > /sys/block/sde/queue/add_random
echo 0 > /sys/block/sdf/queue/add_random

#I/O-ioStats-mods
echo 0 > /sys/block/mmcblk0/queue/iostats
echo 0 > /sys/block/sda/queue/iostats
echo 0 > /sys/block/sdb/queue/iostats
echo 0 > /sys/block/sdc/queue/iostats
echo 0 > /sys/block/sdd/queue/iostats
echo 0 > /sys/block/sde/queue/iostats
echo 0 > /sys/block/sdf/queue/iostats

#I/O-nrRequests-mods
echo 512 > /sys/block/mmcblk0/queue/nr_requests
echo 512 > /sys/block/sda/queue/nr_requests
echo 512 > /sys/block/sdb/queue/nr_requests
echo 512 > /sys/block/sdc/queue/nr_requests
echo 512 > /sys/block/sdd/queue/nr_requests
echo 512 > /sys/block/sde/queue/nr_requests
echo 512 > /sys/block/sdf/queue/nr_requests

#I/O-readAhead-mods
echo 512 > /sys/block/mmcblk0/queue/read_ahead_kb
echo 512 > /sys/block/sda/queue/read_ahead_kb
echo 512 > /sys/block/sdb/queue/read_ahead_kb
echo 512 > /sys/block/sdc/queue/read_ahead_kb
echo 512 > /sys/block/sdd/queue/read_ahead_kb
echo 512 > /sys/block/sde/queue/read_ahead_kb
echo 512 > /sys/block/sdf/queue/read_ahead_kb

#kernel-mods
echo 20 > /proc/sys/kernel/perf_cpu_time_max_percent
echo 0 > /proc/sys/kernel/sched_child_runs_first
echo 25 > /proc/sys/kernel/sched_min_task_util_for_colocation
echo "off" > /proc/sys/kernel/printk_devmsg

exit 0
